language: objective-c

os: osx
osx_image: xcode9.2

script:
    - xcodebuild -project ManOpen.xcodeproj -scheme ManOpen -configuration Development test

after_success:
    - bash <(curl -s https://codecov.io/bash)
