language: objective-c

os: osx
osx_image: xcode9.3

script:
    - xcodebuild -project ManOpen.xcodeproj -scheme ManOpen -configuration Development -quiet test

after_success:
    - bash <(curl -s https://codecov.io/bash)
